version: "3"
services:
  bogos:
    container_name: bogos_1
    command: ["flask", "run", "--host", "0.0.0.0"]
    build:
      context: src
    networks:
      - app-private
    volumes:
      - ./src:/app
      - ./data:/data
    environment:
    - FLASK_ENV=development

  nginx:
    container_name: bogos_nginx_1
    image: nginx:1.17.9-alpine
    # build:
    #   context: nginx
    networks:
      - app-private
    links:
      - bogos
    volumes:
      - ./nginx/files/:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf:ro
      - ./nginx/common.conf:/etc/nginx/common.conf:ro
      - ./nginx/common_location.conf:/etc/nginx/common_location.conf:ro

    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - bogos
networks:
  app-private:
