name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (if needed)
        run: |
          # Add any build steps here if needed
          echo "No build steps needed for static files"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src/static
          branch: gh-pages
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
          single-commit: true
          commit-message: "Deploy to GitHub Pages"
